apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configs
data: {{toYaml .Values.configs | nindent 2}}

---
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
stringData: {{toYaml .Values.secrets | nindent 2}}
