apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-configs
data: {{toYaml .Values.minio.configs | nindent 2}}

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
stringData: {{toYaml .Values.minio.secrets | nindent 2}}

---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: operator-port
      port: 9000
      protocol: TCP
    - name: console-port
      port: 9001
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-07-04T14-25-45Z
          envFrom:
            - configMapRef:
                name: minio-configs
            - secretRef:
                name: minio-secrets
          command: ["minio"]
          args:
            [
              "server",
              "/data",
              "--address",
              ":9000",
              "--console-address",
              ":9001",
            ]
          volumeMounts:
            - mountPath: /data
              name: minio-pvc
  volumeClaimTemplates:
    - metadata:
        name: minio-pvc
      annotations:
        volumeType: local
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 8Gi
